// Generated by CoffeeScript 1.3.3
(function() {
  var SCSim, chai, root, should, _;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  SCSim = root.SCSim;

  _ = root._;

  chai = root.chai;

  should = chai.should();

  SCSim.config.secsPerTick = .5;

  describe('Simulation with one base one worker', function() {
    var base, sim, simRun;
    simRun = new SCSim.SimRun;
    sim = simRun.sim;
    simRun.start();
    base = simRun.gameState.structures.nexus[0];
    return describe('When the base creates a new worker', function() {
      base.say("trainUnit", 'probe');
      return it('the base should receive minerals after some time', function() {
        var i, _i;
        for (i = _i = 1; _i <= 60; i = ++_i) {
          simRun.update();
        }
        return base.behaviors["PrimaryStructure"].mineralAmt.should.be.above(0);
      });
    });
  });

  describe('Simulation with one base and two workers', function() {
    var base, sim, simRun;
    simRun = new SCSim.SimRun;
    sim = simRun.sim;
    simRun.start();
    base = simRun.gameState.structures.nexus[0];
    it('should queue up two workers at base', function() {
      base.say("trainUnit", 'probe');
      base.say("trainUnit", 'probe');
      base.say("trainUnit", 'probe');
      return base.behaviors["Trainer"].queued.length.should.equal(2);
    });
    it('will make the first worker harvest while the 2nd builds', function() {
      while (base.behaviors["Trainer"].queued.length > 0) {
        simRun.update();
      }
      return base.behaviors["PrimaryStructure"].mineralAmt.should.be.above(0);
    });
    it('workers will seek other resources if theirs is taken', function() {
      var timeOut,
        _this = this;
      timeOut = 50;
      simRun.emitter.observe("changeTargetResource", function(e) {
        return timeOut = -999;
      });
      while (!(timeOut-- < 0)) {
        simRun.update();
      }
      return timeOut.should.equal(-999 - 1);
    });
    return it('will find other min patches', function() {
      var harvestedMinPatchIds, i, _i,
        _this = this;
      harvestedMinPatchIds = [];
      simRun.emitter.observe("harvestBegan", function(e) {
        return harvestedMinPatchIds.push(e.simId);
      });
      for (i = _i = 1; _i <= 40; i = ++_i) {
        simRun.update();
      }
      return _(harvestedMinPatchIds).unique().length.should.be.above(1);
    });
  });

}).call(this);
