// Generated by CoffeeScript 1.3.1
(function() {
  var SCSim, chai, root, should, _;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  SCSim = root.SCSim;

  _ = root._;

  chai = root.chai;

  should = chai.should();

  describe("SCSim.GameRules", function() {
    var rules;
    rules = null;
    beforeEach(function() {
      var gameData;
      gameData = new SCSim.GameData;
      gameData.addUnit("testUnit", 10, 20, 1, 1);
      return rules = new SCSim.GameRules(gameData);
    });
    return describe("canTrainUnit()", function() {
      it("should be true if enough supply, gas, min, and tech", function() {
        var hud, result;
        hud = {
          minerals: 10,
          gas: 20,
          supply: 0,
          supplyCap: 100
        };
        result = rules.canTrainUnit("testUnit", hud);
        return result.should.be["true"];
      });
      it("should be false if unit min&gas cost more than our bank", function() {
        var hud, result;
        hud = {
          minerals: 9,
          gas: 19
        };
        result = rules.canTrainUnit("testUnit", hud);
        return result.should.be["false"];
      });
      it("should be false if only unit min cost more than our bank", function() {
        var hud, result;
        hud = {
          minerals: 9,
          gas: 100
        };
        result = rules.canTrainUnit("testUnit", hud);
        return result.should.be["false"];
      });
      return it("should be false if unit would excede supply cap", function() {
        var hud, result;
        hud = {
          minerals: 100,
          gas: 100,
          supply: 0,
          supplyCap: 0
        };
        result = rules.canTrainUnit("testUnit", hud);
        return result.should.be["false"];
      });
    });
  });

  describe("SCSim.Cmd", function() {
    return describe("select()", function() {
      var hud, sim;
      hud = null;
      sim = null;
      beforeEach(function() {
        var simRun;
        simRun = new SCSim.SimRun;
        sim = simRun.sim;
        return hud = simRun.hud;
      });
      return it("should return a fn to select the specified actor from a HUD", function() {
        var cmd, unit;
        unit = sim.makeActor("probe");
        hud.addUnit(unit);
        cmd = SCSim.Cmd.selectUnit("probe");
        return unit.should.equal(cmd(hud));
      });
    });
  });

}).call(this);
