// Generated by CoffeeScript 1.3.1
(function() {

  SCSim.Hud = (function() {

    Hud.name = 'Hud';

    function Hud() {}

    Hud.productionPotential = {};

    return Hud;

  })();

}).call(this);
