// Generated by CoffeeScript 1.3.1
(function() {
  var SimActor, SimEventLog, SimSingletons, SimTimer, root, _,
    __slice = [].slice;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  _ = require('underscore');

  _.mixin({
    rot: function(arr, num) {
      if (num == null) {
        num = 1;
      }
      return this.rest(arr, num).concat(this.first(arr, num));
    },
    containsInstanceOf: function(collection, theType) {
      if (_(collection).isObject()) {
        collection = _(collection).values();
      }
      return _(collection).any(function(i) {
        return i instanceof theType;
      });
    }
  });

  SimSingletons = (function() {

    SimSingletons.name = 'SimSingletons';

    function SimSingletons() {}

    SimSingletons.dependency = {};

    SimSingletons.register = function(proto, instance) {
      this.dependency[proto.name] = instance != null ? instance : new proto;
      return this.dependency[proto.name];
    };

    SimSingletons.get = function(proto) {
      if (this.dependency[proto.name] === void 0) {
        console.error("dependency not found: " + proto.name);
      }
      return this.dependency[proto.name];
    };

    return SimSingletons;

  })();

  SimEventLog = (function() {

    SimEventLog.name = 'SimEventLog';

    function SimEventLog() {
      this.events = {};
      this.eventsToCollect = {};
    }

    SimEventLog.prototype.defaultFormatter = function(e) {
      return e;
    };

    SimEventLog.prototype.event = function(eventName, filter) {
      var _ref;
      return (_ref = this.events[eventName]) != null ? _ref : [];
    };

    SimEventLog.prototype.watchFor = function(eventNames) {
      var e, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = eventNames.length; _i < _len; _i++) {
        e = eventNames[_i];
        this.eventsToCollect[e] = this.defaultFormatter;
        _results.push(this.events[e] = []);
      }
      return _results;
    };

    SimEventLog.prototype.fwatchFor = function(eventName, formatter) {
      var _base, _ref;
      this.eventsToCollect[eventName] = formatter != null ? formatter : this.defaultFormatter;
      return (_ref = (_base = this.events)[eventName]) != null ? _ref : _base[eventName] = [];
    };

    SimEventLog.prototype.log = function(e) {
      var formatter;
      formatter = this.eventsToCollect[e.eventName];
      if (formatter) {
        return this.events[e.eventName].push(formatter(e));
      }
    };

    SimEventLog.prototype.clear = function() {
      this.events = {};
      return this.watchFor(_(this.eventsToCollect).keys());
    };

    SimEventLog.prototype.eventOccurs = function(eventName, timeOut, condition) {
      if (!this.events[eventName]) {
        this.watchFor(eventName);
      }
      return this.event(eventName).length > 0 || timeOut < 0;
    };

    return SimEventLog;

  })();

  SimTimer = (function() {

    SimTimer.name = 'SimTimer';

    function SimTimer() {
      this.tick = 0;
      this.seconds = 0;
    }

    SimTimer.prototype.step = function(steps) {
      if (steps == null) {
        steps = 1;
      }
      this.tick += steps;
      return this.seconds += steps;
    };

    SimTimer.prototype.reset = function() {
      this.tick = 0;
      return this.seconds = 0;
    };

    return SimTimer;

  })();

  SimActor = (function() {

    SimActor.name = 'SimActor';

    function SimActor(defaultStateName) {
      if (defaultStateName == null) {
        defaultStateName = "default";
      }
      this.currentState;
      this.logger = SimSingletons.get(SimEventLog);
      this.time = SimSingletons.get(SimTimer);
      this.currentTransitions;
      this.switchStateTo(defaultStateName);
    }

    SimActor.prototype.switchStateTo = function(sn, a, b, c, d) {
      var _ref;
      this.stateName = sn;
      this.currentState = this["state_" + this.stateName].update.call(this, a, b, c, d);
      this.currentTransitions = this["state_" + this.stateName].messages;
      return (_ref = this["state_" + this.stateName].enterState) != null ? _ref.call(this, a, b, c, d) : void 0;
    };

    SimActor.prototype.say = function(msgName, a, b, c, d) {
      var _ref, _ref1;
      if ((_ref = this.logger) != null) {
        _ref.log({
          eventName: msgName,
          eventTime: this.time.tick,
          simId: this.simId,
          args: [a, b, c, d]
        });
      }
      return (_ref1 = this.currentTransitions[msgName]) != null ? _ref1.call(this, a, b, c, d) : void 0;
    };

    SimActor.prototype.update = function(t) {
      return this.currentState(t);
    };

    SimActor.state = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return this.prototype["state_" + args[0]] = args[1];
    };

    SimActor.defaultState = function(obj) {
      return this.prototype["state_default"] = obj;
    };

    SimActor.prototype.isExpired = function(t) {
      return t <= 0;
    };

    SimActor.prototype.sayAfter = function(timeSpan, a, b, c, d) {
      return function(t) {
        if (this.isExpired(timeSpan--)) {
          return this.say(a, b, c, d);
        }
      };
    };

    SimActor.noopUpdate = function() {
      return function() {};
    };

    return SimActor;

  })();

  root.SimSingletons = SimSingletons;

  root.SimEventLog = SimEventLog;

  root.SimActor = SimActor;

  root.SimTimer = SimTimer;

}).call(this);
