// Generated by CoffeeScript 1.3.1
(function() {
  var SCSim, options, root, runSim, series;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  SCSim = root.SCSim;

  runSim = function(workerCount) {
    var base, data, e, i, sim, _i, _j, _k, _len, _ref;
    sim = new SCSim.EconSim;
    sim.logger.fwatchFor('mineralsCollected', function(e) {
      return [new Date(e.eventTime * 1000), +e.args[0]];
    });
    base = sim.createActor(SCSim.SimBase);
    sim.say('start');
    for (i = _i = 1; 1 <= workerCount ? _i <= workerCount : _i >= workerCount; i = 1 <= workerCount ? ++_i : --_i) {
      base.say('buildNewWorker');
    }
    for (i = _j = 0; _j <= 400; i = ++_j) {
      sim.update();
    }
    data = [];
    _ref = sim.logger.event('mineralsCollected');
    for (_k = 0, _len = _ref.length; _k < _len; _k++) {
      e = _ref[_k];
      data.push(e);
    }
    return data;
  };

  series = [];

  series.push({
    data: runSim(10),
    shadowSize: 0,
    lines: {
      lineWidth: 1
    }
  });

  series.push({
    data: runSim(5),
    shadowSize: 0,
    lines: {
      lineWidth: 1
    }
  });

  options = {
    grid: {
      borderWidth: 0
    },
    xaxis: {
      mode: "time",
      timeformat: "%M:%S"
    }
  };

  $.plot($("#placeholder"), series, options);

}).call(this);
