// Generated by CoffeeScript 1.3.1
(function() {
  var SCSim, b, root, u, _ref;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  SCSim = (_ref = root.SCSim) != null ? _ref : {};

  root.SCSim = SCSim;

  u = function(min, gas, buildTime, supply, actor) {
    return {
      min: min,
      gas: gas,
      buildTime: buildTime,
      supply: supply,
      actor: function() {
        return SCSim[actor];
      }
    };
  };

  b = function(min, gas, buildTime) {
    return {
      min: min,
      gas: gas,
      buildTime: buildTime
    };
  };

  SCSim.config = {
    secsPerTick: .1,
    workerOverlapThreshold: .4
  };

  SCSim.data = {
    units: {
      probe: u(50, 0, 17, 1, "Harvester")
    },
    buildings: {
      pylon: b(100, 0, 25)
    }
  };

}).call(this);
