// Generated by CoffeeScript 1.3.1
(function() {
  var SCSim, root, _, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  SCSim = (_ref = root.SCSim) != null ? _ref : {};

  root.SCSim = SCSim;

  _ = root._;

  SCSim.WarpInBuilder = (function(_super) {

    __extends(WarpInBuilder, _super);

    WarpInBuilder.name = 'WarpInBuilder';

    function WarpInBuilder() {}

    WarpInBuilder.defaultState({
      messages: {
        build: function(name) {}
      }
    });

    return WarpInBuilder;

  })(SCSim.Behavior);

}).call(this);
