// Generated by CoffeeScript 1.3.3
(function() {
  var SCSim, root, _, _ref;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  SCSim = (_ref = root.SCSim) != null ? _ref : {};

  root.SCSim = SCSim;

  _ = root._;

  SCSim.helpers = {
    setupMap: function(sim) {
      var i, minPatch, nexus, probe, _i, _results;
      nexus = sim.makeActor("nexus");
      nexus.say("trainInstantly");
      minPatch = nexus.get("getMostAvailableMinPatch");
      _results = [];
      for (i = _i = 0; _i <= 4; i = ++_i) {
        probe = sim.makeActor("probe");
        probe.say("trainInstantly");
        _results.push(probe.say("gatherFromResource", minPatch));
      }
      return _results;
    }
  };

}).call(this);
