// Generated by CoffeeScript 1.3.3
(function() {
  var SCSim, root, _, _ref;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  SCSim = (_ref = root.SCSim) != null ? _ref : {};

  root.SCSim = SCSim;

  _ = root._;

  SCSim.helpers = {
    setupResources: function(gameState) {
      gameState.resources.minerals = 50;
      gameState.resources.gas = 0;
      gameState.supply.inUse = 0;
      return gameState.supply.cap = 10;
    },
    setupMap: function(sim) {
      var i, nexus, _i, _results;
      nexus = sim.makeActor("nexus");
      nexus.say("trainInstantly");
      _results = [];
      for (i = _i = 0; _i <= 5; i = ++_i) {
        _results.push(nexus.say("trainUnitInstantly", "probe"));
      }
      return _results;
    }
  };

}).call(this);
