// Generated by CoffeeScript 1.3.1
(function() {
  var SCSim, root, _, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  SCSim = (_ref = root.SCSim) != null ? _ref : {};

  root.SCSim = SCSim;

  _ = root._;

  SCSim.WarpInBuilder = (function(_super) {

    __extends(WarpInBuilder, _super);

    WarpInBuilder.name = 'WarpInBuilder';

    function WarpInBuilder() {}

    WarpInBuilder.defaultState({
      messages: {
        build: function(name) {
          return this.sim.say("trainActor", name);
        }
      }
    });

    return WarpInBuilder;

  })(SCSim.Behavior);

  SCSim.Trainable = (function(_super) {

    __extends(Trainable, _super);

    Trainable.name = 'Trainable';

    function Trainable(callbacks) {
      this.callbacks = callbacks != null ? callbacks : [];
      this.buidTime;
      this.startTime;
    }

    Trainable.prototype.instantiate = function() {
      this.buildTime = (SCSim.data.get(this.actor.actorName)).buildTime;
      this.blockActor();
      return this.go("default");
    };

    Trainable.defaultState({
      update: function() {
        return function() {
          if (this.startTime + this.buildTime <= this.time.sec) {
            return this.say("trainingComplete");
          }
        };
      },
      enterState: function() {
        return this.startTime = this.time.sec;
      },
      messages: {
        trainingComplete: function() {
          var c, _i, _len, _ref1, _results;
          this.unblockActor();
          this.go("trained");
          _ref1 = this.callbacks;
          _results = [];
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            c = _ref1[_i];
            _results.push(c());
          }
          return _results;
        }
      }
    });

    Trainable.state("trained", {});

    return Trainable;

  })(SCSim.Behavior);

}).call(this);
